### ISSUE TITLE
Console error message

### ISSUE THREAD

**Issue by jrmneveu** [asdine/pulpe#32]
I don't know how it happened, but an error message has been displayed in the console when I check it.

<img width="383" alt="capture d ecran 2017-01-15 a 23 39 42" src="https://cloud.githubusercontent.com/assets/3194249/21966872/17350e9c-db7c-11e6-968c-42190bda7327.png">

**Comment by asdine** [comment]
Thank you, but this is just a warning and removing it would take more time than necessary. One solution would be to use `browserHistory` instead of `hashHistory` but it's complicated to make this work with `asar` set to true.
Closing for now, will reopen if it gets really annoying
