### ISSUE TITLE
Better display of contentless cards

### ISSUE THREAD

**Issue by asdine** [asdine/pulpe#45]
When we open a card with no description it looks like this:

<img width="609" alt="capture d ecran 2017-01-21 a 18 29 14" src="https://cloud.githubusercontent.com/assets/2102036/22176311/8f7c9214-e007-11e6-9c30-dd6a4246a940.png">

Should we just display the header with no body?

**Comment by jrmneveu** [comment]
In fact, as we are going to allow the user to change the content by a click, we should add a placeholder or something. I will fix this issue in the PR #44
